const LAYOUT = {
  GUTTER: 14,
  GAP: 16,
  FIELD_GAP: 20,
  CORNER: 4,
  FONT_XTRA_SMALL: 10,
  FONT_SMALL: 12,
  FONT_NORMAL: 14,
  FONT_MEDIUM: 16,
  FONT_LARGE: 20,
  TEXT_PADDING: 2,
  CARD_GAP: 16
};

export default LAYOUT;
